## Numpy array and basics

In [1]:
import numpy as np 

### creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : " ,arr_1d)

arr_2d = np.array([[1,2,3] ,[4,5,6]])
print("2d array :" ,arr_2d)

1D array :  [1 2 3 4 5]
2d array : [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [8]:
py_list = [1,2,3]
print("python list multiplication",py_list *2)

np_array = np.array([1,2,3]) #element wise multiplication
print("numpy array multiplication",np_array * 2) # multiplication with array

import time
start = time.time();
py_list = [i*2 for i in range(1000000)]
print("\n List operation time ",time.time()-start)

start =time.time()
np_array = np.arange(1000000) *2
print("\n np array operation time ",time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]

 List operation time  0.06443595886230469

 np array operation time  0.003949880599975586


### creating array from scratch

In [20]:
zeros = np.zeros((3,4))
print("\nzeros matrix",zeros)

ones = np.ones((2,3))
print("\nones matrix :",ones)

full = np.full((3,5),10)
print("Matrix with same value:" ,full)

random = np.random.random((4,3))
print("\nMatrix with random value:" ,random)

sequence = np.arange(0,10,2)
print("\n sequnce array :" ,sequence)


zeros matrix [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones matrix : [[1. 1. 1.]
 [1. 1. 1.]]
Matrix with same value: [[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]

Matrix with random value: [[0.67508004 0.38695275 0.98529271]
 [0.76708397 0.74950494 0.2468084 ]
 [0.45087194 0.42553385 0.29471796]
 [0.49570829 0.84127698 0.19274977]]

 sequnce array : [0 2 4 6 8]


### vector , Matrix and Tensor

In [25]:
vector = np.array([1,2,3])
print("\n Vetor :",vector)

matrix = np.array([[1,2,3],
                   [3,4,5]])
print("\n Matrix :",matrix)

tensor = np.array([[[1,3,4],[1,2,3]],
                    [[4,7,8],[3,9,1]]
                    ])
print("\n Tensor :",tensor)


 Vetor : [1 2 3]

 Matrix : [[1 2 3]
 [3 4 5]]

 Tensor : [[[1 3 4]
  [1 2 3]]

 [[4 7 8]
  [3 9 1]]]


### array properties


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]
                ])
print("shape:" ,arr.shape)
print("dimension :",arr.ndim)
print("size :", arr.size)
print("data type :", arr.dtype)

shape: (2, 3)
dimension : 2
size : 6


### array reshaping

In [30]:
arr = np.arange(12)
print("orignal array :" ,arr)

reshaped = arr.reshape((3,4))
print("reshaped array :" ,reshaped)

flatten = reshaped.flatten()
print("flattened array :" ,flatten)

# ravel return view instead of copy
raveled = reshaped.ravel()
print("raveled array :" ,raveled)

#transpose
transpose = reshaped.T
print("Transposed array :" ,transpose)


orignal array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
