## NUMPY ARRAY OPERATIONS

In [63]:
import numpy as np

In [64]:
arr = np.array([1,2,3,4,5,6,7,8])
print("basic slicing",arr[2:7]) # start from index 2 to index 7
print("with step ", arr[1:8:2]) ##index 1 to 8 with step 2(leaving 1 before next comes)
print("negative indexing",arr[-3]) # 3rd element from end


basic slicing [3 4 5 6 7]
with step  [2 4 6 8]
negative indexing 6


In [65]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element" ,arr_2d[1,2] ) #element of row 2 and column 3.(arr[row,col])
print("entire row :",arr_2d[1]) #entire 2nd row. arr[row]
print("entire col :" , arr_2d[:,1]) #entire 2nd column. arr[:,col]. : represents in every row

specific element 6
entire row : [4 5 6]
entire col : [2 5 8]


## sorting

In [66]:
unsorted = np.array([3,5,1,4,88,56,33,222,1,0])
print("sorted array :",np.sort(unsorted)) #np.sort(arr)-sorts the given array

arr_2d_unsorted = np.array([[3,1],
                   [1,5],
                   [2,3]])
print("sorted each row",np.sort(arr_2d_unsorted,axis=0)) # passing axis as argument for 2d array , axis = 0 means sort whole 2d array
print("sorted each row",np.sort(arr_2d_unsorted,axis=1)) # passing axis as argument for 2d array , axis = 1 means sort rows of  2d array but doesn't change rows position.

sorted array : [  0   1   1   3   4   5  33  56  88 222]
sorted each row [[1 1]
 [2 3]
 [3 5]]
sorted each row [[1 3]
 [1 5]
 [2 3]]


## filter

In [67]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 ==0] # new_array =  oldarray[condition/expression]
print("even numbers",even_number)

even numbers [ 2  4  6  8 10]


filter with mask


In [68]:
mask = numbers > 5
print("numbers greater than 5",numbers[mask]) # existing_array[mask]


numbers greater than 5 [ 6  7  8  9 10]


### fancy indexing vs np.where()


In [69]:
indicies = [0,2,4]
print(numbers[indicies]) #we can access elements of array through giving array of indicies. arr[[index1,index2,...,indexn]]

where_result = np.where(numbers>5) # stores index. np.where(condition)-> returns array of indexes satisfying condition
print("np where :" ,numbers[where_result])

[1 3 5]
np where : [ 6  7  8  9 10]


In [80]:
condition_array = np.where(numbers>5 ) #np.where(conditon)
print(condition_array)
condition_array = np.where(numbers>5,numbers*2,numbers) # np.where(condition,modification1,modification 2)-> apply the modification1 only in elements which satisfy condition and the modiciation 2 in element not satisfying conditon 
print(condition_array)
condition_array = np.where(numbers%2==0,"true","false") # np.where(condition,modification1,modification 2)-> apply the modification1 only in elements which satisfy condition and the modiciation 2 in element not satisfying conditon 
print(condition_array)


(array([5, 6, 7, 8, 9]),)
[ 1  2  3  4  5 12 14 16 18 20]
['false' 'true' 'false' 'true' 'false' 'true' 'false' 'true' 'false'
 'true']


## adding and removing data


In [81]:
arr1 = np.array([1,2,3,4,5,3])
arr2 = np.array([5,5,3,2,6,6])
sum = arr1+arr2 # + adds value of both array rather than concatinating them
print(sum)
combined= np.concatenate((arr1,arr2)) # this concatenate arrays passed as argument
print(combined)


[ 6  7  6  6 11  9]
[1 2 3 4 5 3 5 5 3 2 6 6]


### array compactibility

In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,4,6]) 

print("compatibility shapes", a.shape == b.shape) # checks if shape is equal
print("compatibility shapes", a.shape == c.shape)

compatibility shapes True
compatibility shapes False


In [86]:
orginal = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((orginal,new_row)) #adds new row in a array
print(orginal)
print(new_row)
print(with_new_row)
newcol= np.array(([7],[8]))
with_new_col = np.hstack((orginal,newcol)) # adds new column in a array
print(with_new_col)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [87]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2) #returns array with deleted element . np.delete(array,index)
print(deleted)

[1 2 4 5]
